//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TEAM3OIE2S.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AuditEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AuditEntities object using the connection string found in the 'AuditEntities' section of the application configuration file.
        /// </summary>
        public AuditEntities() : base("name=AuditEntities", "AuditEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuditEntities object.
        /// </summary>
        public AuditEntities(string connectionString) : base(connectionString, "AuditEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuditEntities object.
        /// </summary>
        public AuditEntities(EntityConnection connection) : base(connection, "AuditEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Audit> Audits
        {
            get
            {
                if ((_Audits == null))
                {
                    _Audits = base.CreateObjectSet<Audit>("Audits");
                }
                return _Audits;
            }
        }
        private ObjectSet<Audit> _Audits;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Audits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAudits(Audit audit)
        {
            base.AddObject("Audits", audit);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM3OIE2SDBModels", Name="Audit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Audit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Audit object.
        /// </summary>
        /// <param name="auditID">Initial value of the auditID property.</param>
        public static Audit CreateAudit(global::System.Int32 auditID)
        {
            Audit audit = new Audit();
            audit.auditID = auditID;
            return audit;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 auditID
        {
            get
            {
                return _auditID;
            }
            set
            {
                if (_auditID != value)
                {
                    OnauditIDChanging(value);
                    ReportPropertyChanging("auditID");
                    _auditID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("auditID");
                    OnauditIDChanged();
                }
            }
        }
        private global::System.Int32 _auditID;
        partial void OnauditIDChanging(global::System.Int32 value);
        partial void OnauditIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userID
        {
            get
            {
                return _userID;
            }
            set
            {
                OnuserIDChanging(value);
                ReportPropertyChanging("userID");
                _userID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userID");
                OnuserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _userID;
        partial void OnuserIDChanging(Nullable<global::System.Int32> value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userName
        {
            get
            {
                return _userName;
            }
            set
            {
                OnuserNameChanging(value);
                ReportPropertyChanging("userName");
                _userName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userName");
                OnuserNameChanged();
            }
        }
        private global::System.String _userName;
        partial void OnuserNameChanging(global::System.String value);
        partial void OnuserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBtable
        {
            get
            {
                return _DBtable;
            }
            set
            {
                OnDBtableChanging(value);
                ReportPropertyChanging("DBtable");
                _DBtable = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBtable");
                OnDBtableChanged();
            }
        }
        private global::System.String _DBtable;
        partial void OnDBtableChanging(global::System.String value);
        partial void OnDBtableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String attribute
        {
            get
            {
                return _attribute;
            }
            set
            {
                OnattributeChanging(value);
                ReportPropertyChanging("attribute");
                _attribute = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("attribute");
                OnattributeChanged();
            }
        }
        private global::System.String _attribute;
        partial void OnattributeChanging(global::System.String value);
        partial void OnattributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String access
        {
            get
            {
                return _access;
            }
            set
            {
                OnaccessChanging(value);
                ReportPropertyChanging("access");
                _access = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("access");
                OnaccessChanged();
            }
        }
        private global::System.String _access;
        partial void OnaccessChanging(global::System.String value);
        partial void OnaccessChanged();

        #endregion

    
    }

    #endregion

    
}
