//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TEAM3OIE2S.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SeriesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SeriesEntities object using the connection string found in the 'SeriesEntities' section of the application configuration file.
        /// </summary>
        public SeriesEntities() : base("name=SeriesEntities", "SeriesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SeriesEntities object.
        /// </summary>
        public SeriesEntities(string connectionString) : base(connectionString, "SeriesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SeriesEntities object.
        /// </summary>
        public SeriesEntities(EntityConnection connection) : base(connection, "SeriesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Series> Series
        {
            get
            {
                if ((_Series == null))
                {
                    _Series = base.CreateObjectSet<Series>("Series");
                }
                return _Series;
            }
        }
        private ObjectSet<Series> _Series;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Series EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeries(Series series)
        {
            base.AddObject("Series", series);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM3OIE2SDBModels", Name="Series")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Series : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Series object.
        /// </summary>
        /// <param name="seriesID">Initial value of the seriesID property.</param>
        public static Series CreateSeries(global::System.Int32 seriesID)
        {
            Series series = new Series();
            series.seriesID = seriesID;
            return series;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 seriesID
        {
            get
            {
                return _seriesID;
            }
            set
            {
                if (_seriesID != value)
                {
                    OnseriesIDChanging(value);
                    ReportPropertyChanging("seriesID");
                    _seriesID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("seriesID");
                    OnseriesIDChanged();
                }
            }
        }
        private global::System.Int32 _seriesID;
        partial void OnseriesIDChanging(global::System.Int32 value);
        partial void OnseriesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> originalSeriesStudyID
        {
            get
            {
                return _originalSeriesStudyID;
            }
            set
            {
                OnoriginalSeriesStudyIDChanging(value);
                ReportPropertyChanging("originalSeriesStudyID");
                _originalSeriesStudyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("originalSeriesStudyID");
                OnoriginalSeriesStudyIDChanged();
            }
        }
        private Nullable<global::System.Int32> _originalSeriesStudyID;
        partial void OnoriginalSeriesStudyIDChanging(Nullable<global::System.Int32> value);
        partial void OnoriginalSeriesStudyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String seriesDescription
        {
            get
            {
                return _seriesDescription;
            }
            set
            {
                OnseriesDescriptionChanging(value);
                ReportPropertyChanging("seriesDescription");
                _seriesDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("seriesDescription");
                OnseriesDescriptionChanged();
            }
        }
        private global::System.String _seriesDescription;
        partial void OnseriesDescriptionChanging(global::System.String value);
        partial void OnseriesDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.DateTime seriesDate
        {
            get
            {
                return _seriesDate;
            }
            set
            {
                OnseriesDateChanging(value);
                ReportPropertyChanging("seriesDate");
                _seriesDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("seriesDate");
                OnseriesDateChanged();
            }
        }
        private global::System.DateTime _seriesDate;
        partial void OnseriesDateChanging(global::System.DateTime value);
        partial void OnseriesDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> totalNumberofSlices
        {
            get
            {
                return _totalNumberofSlices;
            }
            set
            {
                OntotalNumberofSlicesChanging(value);
                ReportPropertyChanging("totalNumberofSlices");
                _totalNumberofSlices = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalNumberofSlices");
                OntotalNumberofSlicesChanged();
            }
        }
        private Nullable<global::System.Int32> _totalNumberofSlices;
        partial void OntotalNumberofSlicesChanging(Nullable<global::System.Int32> value);
        partial void OntotalNumberofSlicesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ROIBegin
        {
            get
            {
                return _ROIBegin;
            }
            set
            {
                OnROIBeginChanging(value);
                ReportPropertyChanging("ROIBegin");
                _ROIBegin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ROIBegin");
                OnROIBeginChanged();
            }
        }
        private Nullable<global::System.Int32> _ROIBegin;
        partial void OnROIBeginChanging(Nullable<global::System.Int32> value);
        partial void OnROIBeginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IlliacBif
        {
            get
            {
                return _IlliacBif;
            }
            set
            {
                OnIlliacBifChanging(value);
                ReportPropertyChanging("IlliacBif");
                _IlliacBif = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IlliacBif");
                OnIlliacBifChanged();
            }
        }
        private Nullable<global::System.Int32> _IlliacBif;
        partial void OnIlliacBifChanging(Nullable<global::System.Int32> value);
        partial void OnIlliacBifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comments
        {
            get
            {
                return _comments;
            }
            set
            {
                OncommentsChanging(value);
                ReportPropertyChanging("comments");
                _comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comments");
                OncommentsChanged();
            }
        }
        private global::System.String _comments;
        partial void OncommentsChanging(global::System.String value);
        partial void OncommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ROIEnd
        {
            get
            {
                return _ROIEnd;
            }
            set
            {
                OnROIEndChanging(value);
                ReportPropertyChanging("ROIEnd");
                _ROIEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ROIEnd");
                OnROIEndChanged();
            }
        }
        private Nullable<global::System.Int32> _ROIEnd;
        partial void OnROIEndChanging(Nullable<global::System.Int32> value);
        partial void OnROIEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> totalSlicesInROI
        {
            get
            {
                return _totalSlicesInROI;
            }
            set
            {
                OntotalSlicesInROIChanging(value);
                ReportPropertyChanging("totalSlicesInROI");
                _totalSlicesInROI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalSlicesInROI");
                OntotalSlicesInROIChanged();
            }
        }
        private Nullable<global::System.Int32> _totalSlicesInROI;
        partial void OntotalSlicesInROIChanging(Nullable<global::System.Int32> value);
        partial void OntotalSlicesInROIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> studyID
        {
            get
            {
                return _studyID;
            }
            set
            {
                OnstudyIDChanging(value);
                ReportPropertyChanging("studyID");
                _studyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("studyID");
                OnstudyIDChanged();
            }
        }
        private Nullable<global::System.Int32> _studyID;
        partial void OnstudyIDChanging(Nullable<global::System.Int32> value);
        partial void OnstudyIDChanged();

        #endregion

    
    }

    #endregion

    
}
