//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TEAM3OIE2S.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StudyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StudyEntities object using the connection string found in the 'StudyEntities' section of the application configuration file.
        /// </summary>
        public StudyEntities() : base("name=StudyEntities", "StudyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudyEntities object.
        /// </summary>
        public StudyEntities(string connectionString) : base(connectionString, "StudyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudyEntities object.
        /// </summary>
        public StudyEntities(EntityConnection connection) : base(connection, "StudyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Study> Studies
        {
            get
            {
                if ((_Studies == null))
                {
                    _Studies = base.CreateObjectSet<Study>("Studies");
                }
                return _Studies;
            }
        }
        private ObjectSet<Study> _Studies;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Studies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudies(Study study)
        {
            base.AddObject("Studies", study);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM3OIE2SDBModels", Name="Study")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Study : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Study object.
        /// </summary>
        /// <param name="studyID">Initial value of the studyID property.</param>
        public static Study CreateStudy(global::System.Int32 studyID)
        {
            Study study = new Study();
            study.studyID = studyID;
            return study;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studyID
        {
            get
            {
                return _studyID;
            }
            set
            {
                if (_studyID != value)
                {
                    OnstudyIDChanging(value);
                    ReportPropertyChanging("studyID");
                    _studyID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("studyID");
                    OnstudyIDChanged();
                }
            }
        }
        private global::System.Int32 _studyID;
        partial void OnstudyIDChanging(global::System.Int32 value);
        partial void OnstudyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> originalStudyID
        {
            get
            {
                return _originalStudyID;
            }
            set
            {
                OnoriginalStudyIDChanging(value);
                ReportPropertyChanging("originalStudyID");
                _originalStudyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("originalStudyID");
                OnoriginalStudyIDChanged();
            }
        }
        private Nullable<global::System.Int32> _originalStudyID;
        partial void OnoriginalStudyIDChanging(Nullable<global::System.Int32> value);
        partial void OnoriginalStudyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String studyDescription
        {
            get
            {
                return _studyDescription;
            }
            set
            {
                OnstudyDescriptionChanging(value);
                ReportPropertyChanging("studyDescription");
                _studyDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("studyDescription");
                OnstudyDescriptionChanged();
            }
        }
        private global::System.String _studyDescription;
        partial void OnstudyDescriptionChanging(global::System.String value);
        partial void OnstudyDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.DateTime studyDate
        {
            get
            {
                return _studyDate;
            }
            set
            {
                OnstudyDateChanging(value);
                ReportPropertyChanging("studyDate");
                _studyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("studyDate");
                OnstudyDateChanged();
            }
        }
        private global::System.DateTime _studyDate;
        partial void OnstudyDateChanging(global::System.DateTime value);
        partial void OnstudyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> delay
        {
            get
            {
                return _delay;
            }
            set
            {
                OndelayChanging(value);
                ReportPropertyChanging("delay");
                _delay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("delay");
                OndelayChanged();
            }
        }
        private Nullable<global::System.Int32> _delay;
        partial void OndelayChanging(Nullable<global::System.Int32> value);
        partial void OndelayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> patientID
        {
            get
            {
                return _patientID;
            }
            set
            {
                OnpatientIDChanging(value);
                ReportPropertyChanging("patientID");
                _patientID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("patientID");
                OnpatientIDChanged();
            }
        }
        private Nullable<global::System.Int32> _patientID;
        partial void OnpatientIDChanging(Nullable<global::System.Int32> value);
        partial void OnpatientIDChanged();

        #endregion

    
    }

    #endregion

    
}
